environment:
  PROJECT_FOLDER: "c:/yaml-cpp"
  INSTALL_PREFIX: "c:/install"

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:


# clone directory
clone_folder: "%PROJECT_FOLDER%"

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

install:

# scripts to run before build
before_build:
  - cmake . -DCMAKE_INSTALL_PREFIX=%INSTALL_PREFIX%

# What solutions to build
build:
  project: ALL_BUILD.vcxproj

test_script: 
  - ctest -V
